sudo: false
cache: bundler
services:
  - postgresql
before_script:
  - psql -c 'create database task_manager_test;' -U postgres
  - bin/rake db:migrate RAILS_ENV=test
script: bundle exec rspec
rvm:
  - 2.2.3
gemfile:
  - Gemfile
